language: ruby
sudo: false

notifications:
  email: false
git:
  depth: 1

rvm:
  - 2.3.1
  - 2.4.0
gemfile:
  - Gemfile

before_install:
  - gem install bundler

before_script:
  - nvm install node
  - nvm use node
  - npm install -g mjml@^3.0.0
  - rake prepare
